/*
 * Control juez firmware.c
 *
 * Created: 01/03/2021 03:32:32 p. m.
 * Author : SYSTEMS
 */ 

#include <avr/io.h>
#include <avr/interrupt.h>
//DEFINICION PARA LOS PINES DE ENTRADA Y SALIDA
#define RESET PIN6_bm//RESET Y READY ESTAN AL REVEZ EN EL ESQUEMÁTICO
#define READY PIN3_bm
#define GO PIN7_bm
#define LED_DATOS PIN2_bm
#define LED_ESTATUS PIN1_bm


int main(void){
	//CONFIGURACIÓN DE PINES DE ENTRADA
    PORTA.DIRCLR |= RESET|READY|GO;//PINES DE ENTRADA PARA LOS BOTONES
	PORTA.DIRSET |= LED_DATOS|LED_ESTATUS;//PINES DE SALIDA PARA LOS LEDS DE SALIDA Y LED DE ESTATUS
    PORTA.PIN3CTRL |= PORT_PULLUPEN_bm;//RESISTENCIA DE PULLUP PARA PUERTOS PA3,PA6 Y PA7
	PORTA.PIN6CTRL |= PORT_PULLUPEN_bm;
	PORTA.PIN7CTRL |= PORT_PULLUPEN_bm;
	//CONFIGURACIÓN DE TIMER PARA TRANSMISIÓN DE DATOS
    while (1){
    }
}

